name: Lint

on:
    push:
    pull_request:

jobs:
    yaml-files:
        name: YAML files

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              env:
                  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  php-version: 7.4
                  tools: composer:v2

            - name: Install Composer dependencies (highest)
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "highest"
                  composer-options: "--prefer-dist --prefer-stable"

            - name: Lint yaml
              run: bin/console lint:yaml wrong_yaml.yaml --format github
